### ISSUE TITLE
British MATZ airspaces misclassified

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#203]
Dear all,

I just received feedback from a user of Enroute Flight Navigation, who found that British MATZ airspaces are missing. I investigated and found that the airspaces exist in the openAIP database, but are misclassified and therefore not shown.

One example is "BOSCOMBE DOWN/MIDDLE WALLOP MATZ 126.700", as I can see from the openAIP web site,

https://www.openaip.net/data/airspaces/6287331c21e1215fd0cf1c70?originUrl=%2Fdata%2Fairspaces%3Fpage%3D1%26limit%3D50%26sortDesc%3Dfalse%26search%3DMATZ%26searchOptLwc%3Dtrue

the airspace is classified 

- Type: Other          
- ICAO Class: Special Use Airspace (SUA)

I believe that this is wrong; if at all, then the fact that this is a MATZ can only be deduced from the airspace name. I believe that the classification should be as follows:

- Type: 14: Military Airport Traffic Zone (MATZ)
- ICAO Class: G

Thanks again for this wonderful project!

Best,

Stefan.

**Comment by reskume** [comment]
Will be fixed with the next UK update.

**Comment by kebekus** [comment]
@reskume Thank you for your work! I believe however that the issue is not quite solved yet. A look at the database shows that the MATZ airspaces as now classified as follows

Type: Military Airport Traffic Zone (MATZ) 
ICAO Class: Special Use Airspace (SUA) 

For an example, look at [BOSCOMBE DOWN MATZ](https://www.openaip.net/data/airspaces/62c46f0c6923a12ad441e234?originUrl=%2Fdata%2Fairspaces%3Fpage%3D1%26limit%3D50%26sortBy%3Dtype%26sortDesc%3Dfalse%26search%3Dboscombe%2520down%26searchOptLwc%3Dtrue). While the type ("MATZ") is now correct, **I fear that the ICAO Class is wrong**. In the UK, **MATZ are classified as Airspace G, not SUA**. Could you please have a look? -- Thanks!

**Comment by reskume** [comment]
I'll take a look but I think this issue will never be resolved 100%. The
main problem is the source of input. Since some countries like the UK are
updated from a source file and airspaces are recreated every time, the
parser will set the ICAO class for every defined AC openair token in the
import file. To "fix" the issue, we can set the parser to classify every
found MATZ to class G. This would fix the issue for UK airspaces but may
break things for other countries. That's why the ICAO class SUA is used,
which is some kind of "one size fits all" solution.

It's possible to have country specific parsing instructions for the parser
but that would require a major refactoring of both parser and openaip
backend logic.

For now, I'll change the linked ICAO class for MATZ to "G" since all
current airspaces of type MATZ are within the UK. Things have to be changed
though if there is another country where MATZ has another ICAO class.



Am So., 10. Juli 2022 um 08:19 Uhr schrieb Stefan Kebekus <
***@***.***>:

**Comment by reskume** [comment]
Fixed with new import

**Comment by kebekus** [comment]
Did I ever say 'thank you' for the quick problem fix?

**Thank You**
