### ISSUE TITLE
OpenAIP Airspace Exports - Empty Exports

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#273]
Hello 

This is more of a question. 

Currenlty many countries don't have any airspaces in them. Only a header is in the file. Wouldn't it be better to not export countries where no data is available? 

I currently check if the size is smaller than 384 bytes. But I deem that fragile.

**Comment by lordfolken** [comment]
Somewhat related. It seems the files are exported every day. Would it be possible to do this only when changed? the LastModified tag of the google drive is updated everyday seemingly.

**Comment by reskume** [comment]
This will be fixed with the deployment of the new Core API version. Files that contain no data are removed. Regarding omitting exports where no documents changed: I have to think about this feature as it is not that trivial to implement. If really required, we can open a new ticket to track this particular feature request better.
