### ISSUE TITLE
According to German NFL 2023-1-2726 the airfield call sign Info has to be changed to Radio 

### ISSUE THREAD

**Issue by speed-axel** [openAIP/openaip#274]
According to German NFL 2023-1-2726 published at 2023-02-07 all airfield **Info** call signs have to be changed to **Radio** in Germany, see page 36/37 of the appended NfL.

Please can you change that by a bulk request for all related German airfields.
[NfL I 2023-1-2726.pdf](https://github.com/openAIP/openaip/files/10759746/NfL.I.2023-1-2726.pdf)

**Comment by reskume** [comment]
I assume that you refer to 

`(3) Flugplätze ohne Flugverkehrsdienst durch den Flugleiter an unkontrollierten Flugplätzen ohne AFIS-Anbieter – RADIO`

on page 37. For me this definition is vague (or erroneous, the grammar seems odd) in terms of defining which ground station has to be called RADION instead of INFORMATION. In both (?) described situations, RADIO has to be used in either absence of a "Flugleiter" or an AFIS. But I my be wrong here.

But if I'm not correct, it's still not possible to do a bulk update but would be an update depending on the situation on the airport/airfield.

**Comment by speed-axel** [comment]
Ich denke, dass generelle Problem ist die aktuelle Datenlage in openAIP bzügl. der Rufzeichen von Flugplätzen in Deutschland. Unter dem **Info** Rufzeichen verbergen sich zum Teil auch Flugplätze mit VFR/IFR Gemischtverkehr, AFIS (Aerodrome Flight Information Service) und einer RMZ. Solche Plätze haben dann das Rufzeichen **Information** und nicht **Info**, wie z.B. Strausberg oder Schönhagen im Berliner Raum. Solange die Rufzeichenzuordnung in der Datenbank nicht korrekt ist, kann man natürlich nicht automatisch **Info** in **Radio** umwandeln, weil das ja dann zum Teil auch wieder falsch wäre. 

Zum Ende bleibt wohl nur der Weg, an die Nutzer von openAIP zu appelieren, ihr Flugplatzrufzeichen selber zu aktualisieren.

**Comment by reskume** [comment]
Ja, das ist richtig. Ich hoffe auch dass sich das rumspricht und die Änderungen so nach und nach kommen. Ich schliesse das mal aber behalte das im Hinterkopf.
