### ISSUE TITLE
Download naming / identification

### ISSUE THREAD

**Issue by obetz** [openAIP/openaip#291]
When I start more than one export for different countries, the download list doesn't indicate the selected countries.
All downloads are named "openaip-airports.xml" and the download list has no apparent mapping.

In last year's version, the naming was "openaip_airports_switzerland_ch.aip".

Since "Export Data" requires to select/filter countries anyway, it might be possible to add two letter country indicators to the download name, e.g. openaip-airports_de_at_ch_it.xml if these four countries are selected in the filter.

Even better, the user could enter a custom designator when requesting the export, for example "de-microlight" or "alps".

This user provided designator could be initialized to the country list from the filter as mentioned above, e.g. -de-at-ch-it.

**Comment by reskume** [comment]
Since there are a lot of possible combinations of filters, naming the export files depending on country will not work very well when multiple filters are used to export data. It may be beneficial to add the possibility for the user to specify the file destination for each export. I'll take a look into this. It should be doable fairly easy.

Regarding the last years version: we provide a complete daily database export (like last year) for all countries that follow a strict naming convention. Depending on what you are trying to achieve, this export files will be a better match than manually downloading data.

**Comment by obetz** [comment]
Indeed: Although I always remove heliports from the XML files for decluttering, the prebuilt exports seem to be better suited than selecting countries and airport types every time and putting load on OpenAIP servers.

I just wasn't able to find the information how to download them. Now I figured it out.

**Comment by reskume** [comment]
Destination filename can now be specified when requesting data export via UI.
