### ISSUE TITLE
Easy to find guide for daily export download URLs

### ISSUE THREAD

**Issue by obetz** [openAIP/openaip#292]
Please provide a guide how to create download URLs for the daily exports:
- on a prominent / easy to find place,
- for the average user.

The information provided in https://www.openaip.net/docs just lists the bucket ID but no information how to build an URL. The linked "tutorial" is IMO not suitable for non-programmers and still lacks information as far as I see.

https://groups.google.com/g/openaip/c/srK1GeiVNPM "How to download from Google Bucket (no coding)" doesn't provide the correct information anymore but provides a very good explanation.

In contrast to Lloyd's posting, the URLs now have a dot instead of the last underscore, and the ndgeojson instead of nggeojson, and there is an "asp_extended" object.

Are there more changes?

As far as I see, the current URLs are

https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f/country_type.format where...

"country" is the two letter country code

"type" is the object type:
apt: Airports
asp: Airspace
asp_extended: OpenAir with AY, AI, AF and AG tokens
hgl: Hang Gliding Sites
hot: Hotspots
nav: Navaids
obs: Obstacles
rpp: Reporting Points

"format" is the output format:
cup: Naviter / SeeYou 
geojson
json
mbtiles
ndgeojson (not nggeojson!)
xml (former .aip)
txt: OpenAir or OpenAir Extended

Example:
https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f/at_apt.xml yields Austrian airports in the (deprecated) openAIP XML format, formerly provided as "openaip_airports_austria_at.aip"

It might be worth mentioning that the .XML extension must be changed to .aip after downloading to be recognized by navigation software like LK8000.

**Comment by reskume** [comment]
We provide several was to export data from openaip:

1.  manual export of data by human user via the Web-Application
2. daily system exports
3. JSON REST API which allows realtime interaction and CRU(D) operations
4. use command line utilities like gcloud "gsutil" to interact with files (not thoroughly tested)

Only 1.) and to some extend 4.) is intended to be used by a "human" user. The manual exports via Web-Application supersede the "old" way of simply clicking on pregenerated
download links and now provides custom data exports that have not been possible before to this extend. 
Due to the fact that the number of downloadable files is now already at 10K and will still increase with each new format that is added, the "old"
way was no longer a viable solution of distributing data/files anymore. 

Both 2.) and 3.) are intended to be used by "code" only. Though you can directly "build" download links for files in a GCS bucket if you know the
used naming convention, using a dedicated library is far superior to this as it provides more convenient methods to interact with the files
metadata in the bucket, especially when you want to download lots of files.

As stated in the openaip docs, openaip currently provides those formats:

- JSON (extension '*.json')
- GeoJSON (extension '*.geojson')
- ND-GeoJSON (Newline-delimited GeoJSON - extension '*.ndgeojson')
- OpenAIR (Airspaces only - extension '*.txt')
- OpenAIR - extended (Airspaces only - extension '*_extended.ndgeojson')
- XML (Deprecated ".aip" format - XML schema does not receive updates anymore. Please use the new JSON format! - extension '*.xml')
- CUP (See You) (Airports, navaids and hotspots only - extension '*.cup')
- Mapbox Vector Tiles (MBTiles - extension '*.mbtiles')

This list may change any time when new formats are available. Every file always has a punctuation between that main "name" and the extension. There is no such thing as "_" as written in the groups post.
That is simply a typo. 

Hope this clarifies some things. If you need more help, please describe you use-case and we will find the best way for you to extract
data from openaip.
