### ISSUE TITLE
Verona CTR misclassified

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#297]
Verona CTR is classified as airspace with ICAO Class "D" and Type "Unclassified." As a result, the airspace is not shown correctly in the app "Enroute Flight Navigation." It should be classified as "CTR."

Along with all my complaints: thank you so much for your work on this beautiful project!

**Comment by reskume** [comment]
Is this due to the export data missing the CTR type (e.g. in openair) or is it a "general" error in this document that can be fixed via the web-interface? The later can be easily changed via the web-interface by every user.

**Comment by kebekus** [comment]
@reskume Hi, Stephan. Thank you for the quick reply. I am unsure if I understand your questions correctly. The problem is in the openAIP database; see the attached screenshot. I can fix the issue in the web interface, but will the fix be overridden the next time you auto-import aviation data from Italy?

![Bildschirmfoto vom 2023-04-24 08-04-02](https://user-images.githubusercontent.com/5110976/233915295-aee6a088-5819-4ae8-8a0a-67b4046ebf14.png)

**Comment by reskume** [comment]
Currently only UK is auto-imported since this data is spot-on, is available via github and provides both type and ICAO class and in addition also frequencies and ground station call-signs. Auto-import can only be done on data with this detail. There are plans to do that for US and CA but this will take a bit longer. All other sources are imported by hand. Before import, I try to add the AY tag (if not present) and AF/AG tag if applicable and I also fix errors that I find during this process, such as intersections, duplicate airspaces that are also in the neighboring country and so on. 

We also push the usage of the AI token to have unique identifiers for each airspace in e.g. an openAIR file which would make automated or partial imports much more easy than it is now. But until now, adoption rate of neither AY, AF/AG or AI token is very high as it involves some more work.

I took a quick look into the import file and it seems that most CTRs only have the ICAO class set instead of CTR - I'll check this with the maintainer of the file. Maybe this is intended...

**Comment by reskume** [comment]
As a quick fix, I fixed the Verona CTR type issue. From looking at the import source, it seems like a typical typo.

**Comment by kebekus** [comment]
@reskume Thank you for the extremely prompt action. Incredible.

**Comment by reskume** [comment]
I also received feedback from the original maintainer of the file. It's what I expected: the file only has ICAO classes for AC tags. There has been a change there recently. I already have the April update for Italy at hand but I have to remap everything to the extended openAIR format for import. Hopefully this will remove some more errors that may have been imported as well with the last update.
