### ISSUE TITLE
Missing airspace for KJNX

### ISSUE THREAD

**Issue by ScottStanton** [openAIP/openaip#305]
The class E airspace for KJNX in Clayton NC USA is missing from OpenAIP. The sectional chart shows it as does airnav (https://www.airnav.com/airport/KJNX).
Please add this airspace.

**Comment by reskume** [comment]
The US airspace has been updated with newly available source file. The airspace in question is not included. From the map it's very hard to get an idea what type of airspace this is but I assume this is some kind of ATZ airspace with either ICAO class G or E which may have been left out due to irrelevancy in the source file that we are using. 

There are plans to writing our own airspace parsers for the US airspace. This way we are able to include all airspaces that we can get and hand them over to openaip users and let them decide which to show and hide. But until now we have to stick with the source file though. I'll close this ticket since it's a simple won't fix until our own data ingestion tool is ready.

The issue for the tool can be tracked here: #286
