### ISSUE TITLE
adding frequency to polish FIS airspace did not work

### ISSUE THREAD

**Issue by speed-axel** [openAIP/openaip#314]
Hi,

I tried to add the calling frequency to the polish FIS airspace regions but the data are not taken over into the database after the update.

See here for an change example:

https://www.openaip.net/data/airspaces/64a3db0cd91007cdf79196f0/rfc?originUrl=%2Fdata%2Fairspaces%2F64a3db0cd91007cdf79196f0

**"frequencies": []**, The diff shows the frequency list as red marked but without any content.

**Comment by reskume** [comment]
Hi,

adding frequencies to airspaces work, at least on my side. See the specific airspace and the change history. I assume that the problem is with the actual process of adding a frequency requires a **second confirmation of adding the frequency**. Once you open a new frequency form with "Add new frequency", adding this frequency must be confirmed with another press of the button "Add frequency" below the form. 

Can you please try again if this works for you?

**Comment by speed-axel** [comment]
It seems I have forgotten to commit the frequency change in the special edit mask. I added some frequncies again with frequency commit and will check it after the update next day.
