### ISSUE TITLE
VRS Error

### ISSUE THREAD

**Issue by OK1SLM** [openAIP/openaip#315]
HI,
Recently, some tiles stopped showing in the different map zooms in the Virtual Radar Server program. Hasn't a change been made? I am adding my scrypt.

<script type="text/javascript">

    const OPENAIP_API_KEY = 'my openaip key';

    if(VRS && VRS.globalDispatch && VRS.serverConfig) {
        VRS.globalDispatch.hook(VRS.globalEvent.bootstrapCreated, function (bootStrap) {
            if (bootStrap.hookMapInitialised) {
                bootStrap.hookMapInitialised(function (pageSettings) {
                    if (pageSettings.mapPlugin && pageSettings.mapPlugin.getNativeType() === 'OpenStreetMap') {
                        var map = pageSettings.mapPlugin.getNative();

                        // adds custom openaip layers to VRS base layer
                        L.tileLayer(`https://{s}.api.tiles.openaip.net/api/data/openaip/{z}/{x}/{y}.png?apiKey=${OPENAIP_API_KEY}`).addTo(map);

                    }
                })
                }
        })
        }

</script>

**Comment by reskume** [comment]
The TMS tiles should have been invalided and rebuild multiple times now since this issue was created. Since I assume that every third party client, if it directly uses openaip TMS without any fronted cache system, will now have the new tiles. I don't have VRS to validate this but feel free to re-open if this issue still persists.
