### ISSUE TITLE
Aerodrome names and locations

### ISSUE THREAD

**Issue by mipastgt** [openAIP/openaip#323]
I am just looking at the french AIP and found that it is difficult to compare the original AIP data with the openAIP data.

For example:

The aerodrome "ABBEVILLE" (LFOI) is located at (50 08 32 N/ 001 49 52 E) according to the official AIP but is located at (50°8'35.002"N 1°49'57.000"E) according to openAIP. Do these coordinates both correspond to the ARP and are they supposed to be the same? The difference is big enough so that you can even see it on the map. Reference: https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_30_NOV_2023/Atlas-VAC/PDF_AIPparSSection/VAC/AD/AD-2.LFOI.pdf

Another problem are the names. When you search for the aerodrome "AIRE SUR L'ADOUR" (LFDA) in the openAIP you won't find it because the name is misspelled as "AIRE SUR L ADOUR". Note the missing "'". Aren't the names used in the openAIP supposed to be spelled identically to the ones in the official AIP? Reference: https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_30_NOV_2023/Atlas-VAC/PDF_AIPparSSection/VAC/AD/AD-2.LFDA.pdf

**Comment by reskume** [comment]
OpenAIP data is derived from official AIPs and it is not done by machines but by human contributors. This means that there are definitely differences between those two. Also, some import sources may have treated ARPs other than openAIP, for example some airports also have their ARPs set to the center of the main runway. This is actually what I like best - also since some airports may have multiple ARPs, some of them even KMs away from a landable surface. What is best is up for discussion but it is clear that openAIP will never match an AIP 100%.

When it comes to names, it's the same thing. The import source may not have had the correct naming for the airports. But this can be changed via the web interface. It's not something that we can fix automatically on our side - unfortunately this is a task for the community to correct those errors if found.

Currently v2 of the openaip web-application is being developed. If we are on schedule, we will include a new search logic that will provide better searchability throughout the app.

**Comment by mipastgt** [comment]
Many thanks for the clarification. Will there also be some possibility of a mass import of data in machine readable form? Fiddling with so much data manually is not only cumbersome but also very error prone.
See attached example of how that could look like.
[GEN-0.4.json.zip](https://github.com/openAIP/openaip/files/13686968/GEN-0.4.json.zip)

**Comment by reskume** [comment]
We can always discuss bulk imports or updates but they have to be carefully planned since this can quickly go waywards. All data has to contain metadata that allows the system to relate one item in the database to one item in the imported data. Most of the time, these are the coordinates but this is also error prone and still a lot of work to get it right. And in the end, there will always be a lot of changes that are not applied due to ambiguity and the rest has to be reviewed and applied by hand.
