### ISSUE TITLE
Bale tma / dittingen east and west missing from db

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#353]
Hi

Bale TMA sectors (the ones in switzerland) seem to be missing in todays export. They also do not seem to be in the dB on openaip.net any longer.

Also missing is Dittingen east/west.

https://www.openaip.net/map#9.18/47.3192/7.5805

https://map.geo.admin.ch/mobile.html?selectedNode=node_ch.bazl.luftfahrtkarten-icao2&zoom=3.6069576238421406&bgLayer=voidLayer&layers=ch.bazl.segelflugkarte&topic=ech&lang=en&E=2606923.03&N=1241089.43

**Comment by reskume** [comment]
Those seem to have been accidentally removed during the FR/CH update. There is another big update for FR with all freqs and ground station names in the pipeline. I'll make sure that this will not happen when this one is merged. This area is particularly bad since a lot of files contain these airspaces and when we remove the duplicates, mistakes like these happen. Again, sorry for the inconvenience and thanks a lot for pointing this out!

**Comment by lordfolken** [comment]
Top as ever. Thank you. :-)
