### ISSUE TITLE
Obstacle data?

### ISSUE THREAD

**Issue by rvt** [openAIP/openaip#53]
Is it possible to add obstacle data of know objects like windmills etc?

**Comment by openaip-automator** [comment]
Yep, it's possible. We can implement that with or after the reporting point features has been released.

**Comment by rvt** [comment]
Out of curiosity, what could be the source? I have been looking around quite a bit, bit did not yet found something usefull..

**Comment by reskume** [comment]
We have up-to-date sources for the D-A-CH area but other areas could be sourced from OSM maybe. Did not yet look into this in-depth so just guessing.

**Comment by rvt** [comment]
Nice,

I never realised it was on the map, unfortunatly no hight info for some of them, some do
no height: https://www.openstreetmap.org/api/0.6/node/8456005646
With height: https://www.openstreetmap.org/node/522813762

But it's a good start :)

**Comment by reskume** [comment]
Feature has been implemented. Because official source lack reliable ways to retrieve sources (broken links, missing files, obstacles "only" defined in PDF), the current implementation is to periodically pull the relevant obstacles from OSM. It's not perfect and some obstacles may not be high enough and/or are missing height but at least all have a position. For now this seems to be the best solution because due to the massive amount of obstacles world-wide, this part of the database will never be filled...
