### ISSUE TITLE
Polish TRA are misclassified

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#88]
Dear all,

the TRA airspaces that exist in Poland are misclassified as "OTHER" even though "TRA" explicitly exists as a possible entry for the "type" field. -- Search for "TR 116" to see an example.

Perhaps it might make sense to tweak the importer to look for the string "TR" in the airspace name (… even importing Polish airspace)?

Best,

Stefan.

**Comment by reskume** [comment]
This is an issue with the source openAIR file and it should be fixed there (in the file) in the next airspace import that is done directly via the version2 webapp. 
Another solution would be to adjust the migration script (v1 -> v2) which is currently used to migrate data from v1 -> v2. But this will not reliably extract airspace types from strings since there are too many variations in names (that, once again, are defined in openAIR files...).
